# Generated by Django 6.0.5 on 2026-05-07 08:05

import django.db.models.deletion
import django.utils.timezone
import fines.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('violations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('WAIVED', 'Waived'), ('DISPUTED', 'Disputed')], db_index=True, default='UNPAID', max_length=20)),
                ('due_date', models.DateField()),
                ('waive_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to=settings.AUTH_USER_MODEL)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='violations.violation')),
            ],
            options={
                'db_table': 'fines_fine',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('TELEBIRR', 'TeleBirr'), ('CBE_BIRR', 'CBE Birr'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Card')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fines.fine')),
            ],
            options={
                'db_table': 'fines_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(default=fines.models._receipt_number, max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='fines.payment')),
            ],
            options={
                'db_table': 'fines_receipt',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='FineRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=5)),
                ('points_deducted', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('violation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_rules', to='violations.violationtype')),
            ],
            options={
                'db_table': 'fines_fine_rule',
                'ordering': ['-effective_from'],
                'unique_together': {('violation_type', 'severity', 'effective_from')},
            },
        ),
    ]
