# Generated by Django 6.0.5 on 2026-05-07 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('city', models.CharField(default='Addis Ababa', max_length=100)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('num_lanes', models.SmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('sumo_node_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intersections_intersection',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('EAST', 'East'), ('WEST', 'West')], max_length=10)),
                ('lane_number', models.SmallIntegerField(default=1)),
                ('lane_type', models.CharField(choices=[('THROUGH', 'Through'), ('TURN_LEFT', 'Turn Left'), ('TURN_RIGHT', 'Turn Right'), ('PEDESTRIAN', 'Pedestrian')], default='THROUGH', max_length=20)),
                ('sumo_lane_id', models.CharField(blank=True, max_length=100, null=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='intersections.intersection')),
            ],
            options={
                'db_table': 'intersections_lane',
            },
        ),
        migrations.CreateModel(
            name='SignalState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(default='NS_GREEN', max_length=50)),
                ('green_duration', models.SmallIntegerField(default=30)),
                ('source', models.CharField(choices=[('AI', 'AI Decision'), ('ADMIN_OVERRIDE', 'Admin Override'), ('FIXED_TIMER', 'Fixed Timer')], default='FIXED_TIMER', max_length=20)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_states', to='intersections.intersection')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intersections_signal_state',
                'ordering': ['-activated_at'],
                'get_latest_by': 'activated_at',
            },
        ),
        migrations.CreateModel(
            name='TrafficCamera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_code', models.CharField(max_length=50, unique=True)),
                ('direction', models.CharField(choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('EAST', 'East'), ('WEST', 'West')], max_length=10)),
                ('stream_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='intersections.intersection')),
                ('lane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intersections.lane')),
            ],
            options={
                'db_table': 'intersections_traffic_camera',
            },
        ),
    ]
