# Generated by Django 6.0.5 on 2026-05-07 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intersections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('CONGESTION', 'Congestion'), ('CAMERA_FAILURE', 'Camera Failure'), ('AI_ANOMALY', 'AI Anomaly'), ('HIGH_VIOLATION_RATE', 'High Violation Rate'), ('SYSTEM', 'System')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intersections.intersection')),
            ],
            options={
                'db_table': 'ai_brain_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scenario_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('rl_params', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_brain_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CongestedZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('affected_lanes', models.JSONField(default=list)),
                ('estimated_delay_seconds', models.IntegerField(default=0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congestion_events', to='intersections.intersection')),
            ],
            options={
                'db_table': 'ai_brain_congested_zone',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rl_params', models.JSONField(default=dict)),
                ('sumo_scenario', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_brain_experiment_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RLEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.IntegerField()),
                ('total_reward', models.DecimalField(decimal_places=4, max_digits=10)),
                ('avg_waiting_time', models.DecimalField(decimal_places=2, max_digits=8)),
                ('throughput', models.IntegerField(default=0)),
                ('pedestrian_delay', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('epsilon', models.DecimalField(decimal_places=4, default=1.0, max_digits=6)),
                ('loss', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='ai_brain.aisession')),
            ],
            options={
                'db_table': 'ai_brain_rl_episode',
                'ordering': ['episode_number'],
                'unique_together': {('session', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='SignalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(max_length=50)),
                ('duration_seconds', models.SmallIntegerField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_brain.rlepisode')),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_decisions', to='intersections.intersection')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_decisions', to='ai_brain.aisession')),
            ],
            options={
                'db_table': 'ai_brain_signal_decision',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ai_brain.aisession')),
            ],
            options={
                'db_table': 'ai_brain_simulation_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
