# Generated by Django 6.0.5 on 2026-05-07 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intersections', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='MINOR', max_length=10)),
                ('points_deducted', models.SmallIntegerField(default=0)),
                ('legal_reference', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'violations_violation_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('AI_DETECTION', 'AI Detection'), ('OFFICER_FIELD', 'Officer Field')], max_length=20)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('UNDER_REVIEW', 'Under Review'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_SYNC', 'Pending Sync'), ('SYNCED', 'Synced'), ('ACKNOWLEDGED', 'Acknowledged'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], db_index=True, default='DETECTED', max_length=20)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='MINOR', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('detected_speed', models.SmallIntegerField(blank=True, null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('driver_license', models.CharField(blank=True, max_length=50)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('vehicle_type_field', models.CharField(blank=True, max_length=50)),
                ('detected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intersections.trafficcamera')),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='intersections.intersection')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_violations', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='vehicles.vehicle')),
                ('violation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='violations.violationtype')),
            ],
            options={
                'db_table': 'violations_violation',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/')),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('source', models.CharField(choices=[('CAMERA', 'Camera'), ('OFFICER_UPLOAD', 'Officer Upload')], default='OFFICER_UPLOAD', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='violations.violation')),
            ],
            options={
                'db_table': 'violations_violation_evidence',
            },
        ),
        migrations.CreateModel(
            name='ViolationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='violations.violation')),
            ],
            options={
                'db_table': 'violations_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['status', '-detected_at'], name='violations__status_a0293f_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['vehicle', '-detected_at'], name='violations__vehicle_7e4fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['officer', '-detected_at'], name='violations__officer_fac9f9_idx'),
        ),
    ]
